cache: pip

matrix:
  fast_finish: true
  include:
    - name: "Black"
      env: RUN=black
      language: python
      python: 3.7
      os: linux
      dist: bionic

install:
- pip install pycodestyle
script:
- pycodestyle kivyauth/android/__init__.py

after_failure:
  - sleep 10;
  - echo == End ==

deploy:
  skip_existing: true
  provider: pypi
  user: "__token__"
  password: ${{ secrets.PASSWORD }}
  distributions: "sdist bdist_wheel"
  on:
    tags: true
